apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080 # the port the service listens to
      targetPort: 8080 # the port to send the traffic to on the pods

