apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.service.name }}
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80 # the port the service listens to
      targetPort: {{ .Values.backend.port }} # the port to send the traffic to on the pods

